language: java
jdk: oraclejdk8
sudo: required
env:
  global:
  - GH_PROJECT_NAME: IntelliJ-Key-Promoter
  - GIT_AUTHOR_NAME: TravisCI
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`
  - GRADLE_USER_HOME=`pwd`/.gradle

before_script:
    - chmod +x gradlew
